# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('user', models.CharField(max_length=100)),
                ('num', models.IntegerField()),
                ('url', models.CharField(max_length=100)),
                ('sub', models.IntegerField()),
            ],
            options={
                'db_table': 'showprogress_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NagoyanSakura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nagoyan_sakura',
                'managed': False,
            },
        ),
    ]
